### ISSUE TITLE
Should allow an IP as an --endpoint

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/surge#105]
Expected this to work:

```sh
surge -e 192.168.0.16:5001
```

Actual:

```sh
/Users/Kenneth/Sites/sintaxi/surge/lib/middleware/util/helpers.js:65
      if (e) throw e
                   ^
Error: Invalid protocol: 172.16.35.255:
    at Request.self._buildRequest (/Users/Kenneth/Sites/sintaxi/surge/node_modules/request/request.js:355:53)
    at Request.init (/Users/Kenneth/Sites/sintaxi/surge/node_modules/request/request.js:533:10)
    at new Request (/Users/Kenneth/Sites/sintaxi/surge/node_modules/request/request.js:99:8)
    at request (/Users/Kenneth/Sites/sintaxi/surge/node_modules/request/index.js:54:11)
    at /Users/Kenneth/Sites/sintaxi/surge/lib/middleware/util/helpers.js:64:5
    at /Users/Kenneth/Sites/sintaxi/surge/lib/middleware/auth.js:21:44
    at Interface.onLine (/Users/Kenneth/Sites/sintaxi/surge/node_modules/read/lib/read.js:111:5)
    at Interface.emit (events.js:107:17)
    at Interface._onLine (readline.js:214:10)
    at Interface._line (readline.js:553:8)
```

This would make testing on Window VMs a lot easier for us. Right now something (possibly [parse-url-as-address](https://github.com/isaacs/url-parse-as-address)?) doesn’t expect to get an IP.

**Comment by kennethormandy** [comment]
This works in some Windows terminals already, and should work in others if you add quotes around it. Apparently I just don’t know how to use Windows. :wind_chime:
