### ISSUE TITLE
Shouldn’t on protocol from CNAME file when running `surge ssl`

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/surge#110]
My project just had `CNAME` file in it, and then I ran a `surge ssl`, and it pre-populated it with _http://implicatetype.com_. What it actually needed to be was _implicatetype.com_, but I had the former in my `CNAME` file, so it used that literally:

![out2](https://cloud.githubusercontent.com/assets/1581276/7972458/7428d366-0a01-11e5-9c3f-0107efd8f1d4.gif)

I would either expect the SSL command to accept the protocol and just ignore it, or for it to populate it with what’s in the CNAME file and not include the protocol, or both.

**Comment by kennethormandy** [comment]
This also happens if you upload a pem file but decide not to pay, and then try to deploy to a non-`https` domain. Confusing! Here’s how to reproduce:

1. `touch example.pem`
2. `surge ssl`, and give it a subdomain like `example.surge.sh` and the `example.pem` file
3. Answer `no` when asked for payment
4. Bail out with <kbd>CRTL</kbd>+<kbd>C</kbd>
5. Run `surge --project ./ --domain example.surge.sh`

You’ll get: 

```
undefined:1
<html><body><h1>502 Bad Gateway</h1>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request.tick (/Users/Kenneth/Sites/sintaxi/surge/lib/middleware/deploy.js:77:27)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/Kenneth/Sites/sintaxi/surge/node_modules/request/request.js:994:12)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
```

If you try step 5 again, and run: `surge --project ./ --domain https://example.surge.sh` then it will work.
