### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by mphasize** [sintaxi/surge#113]
Surge is beginning to deploy and then suddenly encounters a `SyntaxError`.

```
upload: [===                 ] 17%, eta: 1.4s
undefined:1
{"type":"progress","id":"upload","written":1717500,"total"
                                                          
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request.tick (/.../surge/lib/middleware/deploy.js:77:27)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/.../surge/node_modules/request/request.js:994:12)
    at IncomingMessage.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
```

I've seen this happening on Travis builds and on my local machine.

Worse: It looks like this doesn't fail with an error code, since Travis still thinks that everything worked fine.
`Done. Your build exited with 0.`

**Comment by kennethormandy** [comment]
Hey, thanks for reporting this. Right now the CLI assumes success by default, which we definitely plan on changing https://github.com/sintaxi/surge/issues/70#issuecomment-78808197.

I haven’t seen the rest of that problem before, though. Would you mind sharing any more details we could try and use to reproduce it? Or the project URL you were publishing to?

Thanks!

**Comment by mphasize** [comment]
@kennethormandy Good to hear about failing by default.

Unfortunately I don't have many more details on the problem and I can't share (at least publicly here) the URL I'm publishing to. But if you check your receipts, you'll find me under 2415-1056.

The project is an Ember app built with ember-cli. I couldn't find any conditions that would reliably reproduce the issue.

**Comment by koddsson** [comment]
I was getting this regularly as well until I made some minor changes in `deploy.js`. 

Here's my error: 
```
             upload: [====================] 100%, eta: 0.0s
             upload: [====================] 99%, eta: 0.0sundefined:1
{"type":"progress","id":

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request.tick (/usr/local/lib/node_modules/surge/lib/middleware/deploy.js:77:27)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:994:12)
    at IncomingMessage.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
```

I can open up a PR with my changes if you'd like.

**Comment by kennethormandy** [comment]
@koddsson Sure, thanks! If you don’t mind we’d like to check it out. Mind sharing what OS, version of Node, and version of Surge you were using too, so we can try and reproduce it?

**Comment by koddsson** [comment]
I added the info in the PR @kennethormandy
