### ISSUE TITLE
surge teardown error: `validDomain is not defined`

### ISSUE THREAD

**Issue by onderweg** [sintaxi/surge#117]
While using the `teardown` command in v0.14.1, I get the following error:

```
/usr/local/lib/node_modules/surge/lib/middleware/teardown.js:56
        if (err || !validDomain(domain)) {
                    ^
ReferenceError: validDomain is not defined
    at /usr/local/lib/node_modules/surge/lib/middleware/teardown.js:56:21
    at Interface.onLine (/usr/local/lib/node_modules/surge/node_modules/read/lib/read.js:111:5)
    at Interface.emit (events.js:107:17)
    at Interface._onLine (readline.js:214:10)
    at Interface._line (readline.js:553:8)
    at Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
    at ReadStream.emit (events.js:110:17)
    at readline.js:1175:14
    at Array.forEach (native)
````
This happens in interactive mode (with domain not supplied as argument).

When I do supply domain as argument (`surge teardown domain.sh`), I get the following error:

```
Aborted - No such file or directory.
```

**Comment by RE-o** [comment]
Same problem here: ubuntu 14.04, node 0.10.38, surge 0.14.1.

**Comment by sintaxi** [comment]
Thanks for reporting. Resolved in surge v0.14.2.

**Comment by onderweg** [comment]
Perfect :+1:

**Comment by RE-o** [comment]
Excellent
