### ISSUE TITLE
Should recognise the domain with the protocol when running surge plus

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/surge#137]
When you run `surge plus`, it should allow you to enter a domain even if you include `http` or `https`. This should be the same as the other domain inputs in the CLI.

```
☞  surge plus

              email: kenneth@chloi.io
              token: *****************
             domain: http://kennethormandy.com
undefined:1
<!DOCTYPE html><!--[if lt IE 9]><html class="ie"><![endif]-->
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/Users/Kenneth/.nvm/versions/node/v0.12.7/lib/node_modules/surge/lib/middleware/plus.js:28:26)
    at Request.self.callback (/Users/Kenneth/.nvm/versions/node/v0.12.7/lib/node_modules/surge/node_modules/request/request.js:123:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/Kenneth/.nvm/versions/node/v0.12.7/lib/node_modules/surge/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/Kenneth/.nvm/versions/node/v0.12.7/lib/node_modules/surge/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by kennethormandy** [comment]
This was fixed as part of the consolidation of domain checking that happened in v0.17.0.
