### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by thebetterjort** [sintaxi/surge#298]
Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)

Running gatsby build .. cd public/ surge renders this..
My corporate proxy has SSL decrpytion. Surge will not trust our org certs (although it should). How do I disable this check, soI can deploy>?

**Comment by antoine-hebert-ia** [comment]
Same here

**Comment by walchko** [comment]
It is probably your corporate firewall. I have seen this before and if you talk with your IT people, they should be able to allow traffic through the firewall to surge.sh without messing with it.

**Comment by ronskie69** [comment]
same prob here...
