### ISSUE TITLE
Cannot publish from node 0.8.10 with surge@0.20.1

### ISSUE THREAD

**Issue by jacques** [sintaxi/surge#309]
I keep getting:

```
$ ENDPOINT=surge.sh surge list

undefined:1
<!DOCTYPE html><html><head><head><meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no"><link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css"><style>body{
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/surge/lib/middleware/util/helpers.js:124:30)
    at Request.self.callback (/usr/local/lib/node_modules/surge/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
$ ENDPOINT=surge.surge.sh surge list

undefined:1
<!DOCTYPE html><html><head><head><meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no"><link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css"><style>body{
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/surge/lib/middleware/util/helpers.js:124:30)
    at Request.self.callback (/usr/local/lib/node_modules/surge/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by giacomoalonzi** [comment]
Same problem here, I rolled back to 0.19 but surge not upload updated file
```
       email: my@emaul
       token: *****************
       project path: /path/to/project
       size: 43 files, 23.5 MB
       domain: myaddress.surge.sh
```
any hint?

**Comment by leewp14** [comment]
Finally someone same with me. This happened to me when I'm halfway deploying my website. 
And I tried to relogin into surge by logging out, and now couldnt login back again :cry:  
![screenshot_2018-03-07_21-09-41](https://user-images.githubusercontent.com/17796518/37096442-91fedd96-2253-11e8-8cf7-8dfa7f2e9379.png)

**Comment by balupton** [comment]
Title should be updated as this is not just node 0.10

```
23:56:02:/Users/balupton/Projects/docpad/docpad:beta
> node -v
v9.7.1
23:56:05:/Users/balupton/Projects/docpad/docpad:beta
> npm i -g surge
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/balupton/.nvm/versions/node/v9.7.1/bin/surge -> /Users/balupton/.nvm/versions/node/v9.7.1/lib/node_modules/surge/lib/cli.js
+ surge@0.20.1
updated 1 package in 3.674s
23:56:13:/Users/balupton/Projects/docpad/docpad:beta
> surge -v

undefined:1
<!DOCTYPE html><html><head><head><meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no"/><link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css"/><style>body{
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/balupton/.nvm/versions/node/v9.7.1/lib/node_modules/surge/lib/middleware/util/helpers.js:124:30)
    at Request.self.callback (/Users/balupton/.nvm/versions/node/v9.7.1/lib/node_modules/surge/node_modules/request/request.js:186:22)
    at Request.emit (events.js:127:13)
    at Request.<anonymous> (/Users/balupton/.nvm/versions/node/v9.7.1/lib/node_modules/surge/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:127:13)
    at IncomingMessage.<anonymous> (/Users/balupton/.nvm/versions/node/v9.7.1/lib/node_modules/surge/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:219:13)
    at IncomingMessage.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
```

**Comment by leewp14** [comment]
here is node 8.9.4
```
leewp14@CTK942S:~$ node -v
v8.9.4
```

**Comment by balinterdi** [comment]
I also have problems, Surge doesn't deploy the updated assets.

> node: 8.9.0
> surge: 0.17.2

**Comment by sintaxi** [comment]
A DNS issue was just resolved. This was human error on my part. 

There may still be an issue with `surge list` on some accounts that is a separate issues though. Let me know your findings if your still see things that are broken.

**Comment by giacomoalonzi** [comment]
Fixed for me on 0.19!

**Comment by segunmicheal27** [comment]
issue on 
node: v14.17.0
as well

**Comment by segunmicheal27** [comment]
this is error we got

Invalid or unexpected token

**Comment by SimonSomlai** [comment]
```
npx surge@0.19 ./dist 
```
fixed it for me
