### ISSUE TITLE
error running surge

### ISSUE THREAD

**Issue by klode** [sintaxi/surge#311]
Today I pushed an update to my surge website, the command was successful but the update was not reflected on the site. 

I then tried to push on a new domain name but got
```
{ Error: write EPIPE
    at _errnoException (util.js:999:13)
    at WriteWrap.afterWrite [as oncomplete] (net.js:883:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
```

Also "surge list" command was  not working giving the following error 
```html
undefined:1
<!DOCTYPE html><html><head><head><meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no"><link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css"><style>body{
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/surge/lib/middleware/list.js:18:21)
    at Request.self.callback (/usr/local/lib/node_modules/surge/node_modules/request/request.js:123:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:164:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

So I tried to npm -g uninstall surge and inpm -g install again. Now "surge" command  fails with the following  Error

```html
undefined:1
<!DOCTYPE html><html><head><head><meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no"><link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css"><style>body{
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/surge/lib/middleware/util/helpers.js:124:30)
    at Request.self.callback (/usr/local/lib/node_modules/surge/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
```

**Comment by klode** [comment]
this is now working.

**Comment by keligijus** [comment]
@klode how did you fix this? I am experiencing a very similar issue
