### ISSUE TITLE
Crash on start on Ubuntu 16.04

### ISSUE THREAD

**Issue by aegroto** [sintaxi/surge#337]
Whenever i try to run surge on my Ubuntu 16.04 machine I get this stacktrace:

```
/usr/local/lib/node_modules/surge/node_modules/inquirer/lib/ui/prompt.js:3
var { defer, empty, from, of } = require('rxjs');
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/inquirer/lib/inquirer.js:19:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by sintaxi** [comment]
what version of node are you on?

**Comment by aegroto** [comment]
```
node -v
v4.2.6
```
I installed it from Ubuntu's repositories.

**Comment by aegroto** [comment]
Solved updating NodeJs following these instructions: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
