### ISSUE TITLE
tunneling socket could not be established

### ISSUE THREAD

**Issue by galiarmero** [sintaxi/surge#373]
I executed `surge` behind a corporate proxy. After typing email and password, I got this error:

```
C:\Users\lipsum\AppData\Roaming\npm\node_modules\surge\lib\middleware\util\helpers.js:146
      if (e) throw e
             ^

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80
    at ClientRequest.onError (C:\Users\lipsum\AppData\Roaming\npm\node_modules\surge\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I have proxy configurations in place for npm and env variables. Is access via proxies not supported?

**Comment by Njinga** [comment]
I have nearly the same problem but for me there is cause=connect  ECONNREFUSED 127.0.0.1:80
    at ClientRequest.onError (C:\Users\PC\AppData\Roaming\npm\node_modules\surge\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
