### ISSUE TITLE
Issues with surge list in CLI

### ISSUE THREAD

**Issue by 2lach** [sintaxi/surge#388]
### Hey
First of all  ❤️surge.sh awesome job @sintaxi!

Today I'am having some issues with `surge list`

**Description**
I get the following error on `surge list`
but the rest of the CLI works without a hitch wondering if anybody else have this issue/knows a way to fix it?

**Error**
```Bash
❯ surge list

/usr/local/lib/node_modules/surge/lib/middleware/list.js:44
          project.timeAgoInWords.grey,
                                 ^

TypeError: Cannot read property 'grey' of undefined
    at /usr/local/lib/node_modules/surge/lib/middleware/list.js:44:34
    at Array.forEach (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/surge/lib/middleware/list.js:33:12)
    at Request.self.callback (/usr/local/lib/node_modules/surge/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
```

**Specs**:
![surge-issue](https://user-images.githubusercontent.com/11457600/70515724-14d66400-1b36-11ea-82b6-49f1742c9a67.png)

**Comment by sintaxi** [comment]
Thanks for the detailed report. This may be a data integrity issue. Do you mind emailing `support@surge.sh` with your email address that you use on surge so that we can have a look at your projects?

**Comment by sintaxi** [comment]
...also, thanks for the kind words :)

**Comment by 2lach** [comment]
Sure thing 👍

**Comment by 2lach** [comment]
Hello @sintaxi hope all is well! 
Im curious if you have any updates regarding this issue? 

Have a good one 👍

**Comment by sintaxi** [comment]
Thanks for the reminder. You should be all good now. Turned out to be a data integrity issue. Let me know if things are all good on your end now.

**Comment by 2lach** [comment]
And..... It looks good 👍Tnx

Anything I need to do on my end in regards to the data integrity issue?
