### ISSUE TITLE
Surge Card Throws Error

### ISSUE THREAD

**Issue by v-patel** [sintaxi/surge#390]
I get the following error when attempting to add a card to surge:
```
undefined:1
<html><body><h1>502 Bad Gateway</h1>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/surge/lib/middleware/setcard.js:40:24)
    at Request.self.callback (/usr/local/lib/node_modules/surge/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by v-patel** [comment]
Was not accepting first two cards I tried, worked on third one
