### ISSUE TITLE
Error in travis while running command

### ISSUE THREAD

**Issue by Shekharrajak** [sintaxi/surge#395]
Hi,

I have installed surge in travis build and running the surge command but getting these error:

```
/home/travis/.nvm/v0.10.48/lib/node_modules/surge/node_modules/cli-table3/src/table.js:4
class Table extends Array {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/.nvm/v0.10.48/lib/node_modules/surge/node_modules/cli-table3/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by Shekharrajak** [comment]
One can see the error here: https://github.com/numpy/numpy.org/runs/452977872
