### ISSUE TITLE
Trap errors on invalid command

### ISSUE THREAD

**Issue by silentrob** [sintaxi/surge#44]
./surge/lib/cli.js -help

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: "boolean" == "string"
    at parse (/Users/robellis/projects/surge/surge/node_modules/url-parse-as-address/index.js:9:10)
    at module.exports (/Users/robellis/projects/surge/surge/lib/middleware/endpoint.js:4:18)
    at next (/Users/robellis/projects/surge/surge/lib/middleware/util/skin.js:11:11)
    at module.exports (/Users/robellis/projects/surge/surge/lib/middleware/util/skin.js:14:10)
    at module.exports (/Users/robellis/projects/surge/surge/lib/surge.js:5:10)
    at Object.<anonymous> (/Users/robellis/projects/surge/surge/lib/cli.js:18:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by sintaxi** [comment]
done

**Comment by silentrob** [comment]
SHA for referene 827ad6de0c7d7ea832837a2196ab03cc742c4e69
