### ISSUE TITLE
running 'surge' in build folder generates the following...

### ISSUE THREAD

**Issue by sagaquisces** [sintaxi/surge#450]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null
    at validateString (internal/validators.js:121:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at module.exports (/Users/michaeldunlap/.nvm/versions/node/v14.8.0/lib/node_modules/surge/lib/middleware/_shared/_protocol.js:5:17)
    at next (/Users/michaeldunlap/.nvm/versions/node/v14.8.0/lib/node_modules/surge/lib/util/skin.js:20:11)
    at exports.suggestDomainFromGenerator (/Users/michaeldunlap/.nvm/versions/node/v14.8.0/lib/node_modules/surge/lib/middleware/_shared/discovery.js:38:10)
    at next (/Users/michaeldunlap/.nvm/versions/node/v14.8.0/lib/node_modules/surge/lib/util/skin.js:20:11)
    at exports.setDomainFromCname (/Users/michaeldunlap/.nvm/versions/node/v14.8.0/lib/node_modules/surge/lib/middleware/_shared/discovery.js:31:10)
    at next (/Users/michaeldunlap/.nvm/versions/node/v14.8.0/lib/node_modules/surge/lib/util/skin.js:20:11)
    at stub (/Users/michaeldunlap/.nvm/versions/node/v14.8.0/lib/node_modules/surge/lib/surge.js:189:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by sintaxi** [comment]
Thanks for reporting!

This has been fixed in `v0.24.0-rc.8` which can be installed with `npm install -g surge@edge`
