### ISSUE TITLE
"surge ssl" -- SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ktg5** [sintaxi/surge#454]
Hello, I'm trying to get my SSL ticket onto my server, but it keeps throwing me the error below:

`$ surge ssl

         domain: http://ktg5.online
       pem file: surge.pem
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.<anonymous> (/usr/local/lib/node_modules/surge/lib/middleware/ssl.js:29:24)
    at Request.emit (events.js:203:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/request/request.js:1073:12)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:974:34)
    at resume_ (_stream_readable.js:955:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

Does anyone know what can be done to solve this?

**Comment by sintaxi** [comment]
Hi @ktg5,

Do you mind reporting the version of surge, nodejs that you are running (`surge --version; node --version`) , along with the operating system you are using?

Meanwhile, you may want to try out the edge version of surge which has some nice SSL provisioning features that mainline does not. You can install that via `npm install -g surge@edge`. See https://github.com/sintaxi/surge/discussions/446 for more details.

**Comment by ktg5** [comment]
surge -- `0.23.0`
node -- `10.19.0`

**Comment by ktg5** [comment]
Any update to this?...
