### ISSUE TITLE
surge bust throws error 502

### ISSUE THREAD

**Issue by shenoa** [sintaxi/surge#484]
Surge v0.24.0-rc.12
Node.js v17.0.1

While trying to troubleshoot a missing resource problem I ran a `surge bust` and received the following 502 error:

```
surge bust [project domain]

undefined:1
<html><body><h1>502 Bad Gateway</h1>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/shenoa/.nvm/versions/node/v17.0.1/lib/node_modules/surge/node_modules/surge-sdk/lib/sdk.js:513:24)
    at Request.self.callback (/Users/shenoa/.nvm/versions/node/v17.0.1/lib/node_modules/surge/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/Users/shenoa/.nvm/versions/node/v17.0.1/lib/node_modules/surge/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/shenoa/.nvm/versions/node/v17.0.1/lib/node_modules/surge/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1340:12)
```

**Comment by sintaxi** [comment]
Old ticket. Issue resolved. Closing.
