### ISSUE TITLE
surge card throws 502

### ISSUE THREAD

**Issue by robshep** [sintaxi/surge#501]
Hi,
Trying to use `surge card` to enable PDF files....

```undefined:1
<html><body><h1>502 Bad Gateway</h1>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/rob/.nvm/versions/node/v16.19.1/lib/node_modules/surge/lib/middleware/setcard.js:40:24)
    at Request.self.callback (/home/rob/.nvm/versions/node/v16.19.1/lib/node_modules/surge/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/rob/.nvm/versions/node/v16.19.1/lib/node_modules/surge/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/rob/.nvm/versions/node/v16.19.1/lib/node_modules/surge/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
```

**Comment by sintaxi** [comment]
Old ticket. Issue resolved. Closing.
