### ISSUE TITLE
Exit during password prompt

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/surge#53]
if you ctrl-c during the password prompt, the CLI throws an error:

   /usr/local/lib/node_modules/surge/lib/middleware/auth.js:32
        helpers.fetchToken(req.argv.endpoint)(req.email, result.password, func
                                                               ^
    TypeError: Cannot read property 'password' of undefined
    at /usr/local/lib/node_modules/surge/lib/middleware/auth.js:32:64
    at /usr/local/lib/node_modules/surge/node_modules/prompt/lib/prompt.js:316:20
    at /usr/local/lib/node_modules/surge/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:136:21
    at assembler (/usr/local/lib/node_modules/surge/node_modules/prompt/lib/prompt.js:282:18)
    at /usr/local/lib/node_modules/surge/node_modules/prompt/lib/prompt.js:322:20
    at /usr/local/lib/node_modules/surge/node_modules/prompt/lib/prompt.js:510:14
    at onError (/usr/local/lib/node_modules/surge/node_modules/prompt/node_modules/read/lib/read.js:94:12)
    at Interface.<anonymous> (/usr/local/lib/node_modules/surge/node_modules/prompt/node_modules/read/lib/read.js:66:5)
    at Interface.emit (events.js:92:17)
    at Interface._ttyWrite (readline.js:621:16)

**Comment by kennethormandy** [comment]
This is fixed now, thanks for reporting @cfjedimaster!

![out](https://cloud.githubusercontent.com/assets/1581276/7847820/188ec442-047b-11e5-8b69-76af1ee1f492.gif)
